### ISSUE TITLE
Initial refactor

### ISSUE THREAD

**Issue by onbjerg** [aragon/aragon-dev-cli#4]
The code is a bit messy, so we'll need to do some initial cleaning.

- [ ] #1: Move handlers into own files
- [ ] #2: Create multiple reporters
- [ ] #3: Abstract APM storage providers
